name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: ./gradlew build --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk


      - name: Run Lint
        run: ./gradlew lint

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest